### ISSUE TITLE
description of cost function wrong?

### ISSUE THREAD

**Issue by dymockb** [learn-co-curriculum/dsc-2-14-11-gradient-descent-step-sizes#1]
The mark-down text between the first two python cells reads:

In our cost function below, you can see the sequential values of  b  and the related RSS values (given a constant value  m ).

Should this instead be the other way around - it is b that is held constant?  Would the following be correct?

In our cost function below, you can see the sequential values of  m  and the related RSS values (given a constant value  b ).

**Comment by fpolchow** [comment]
fixed. thanks for flagging!
